### ISSUE TITLE
Allow multiple paths to be specified for <inputPath>

### ISSUE THREAD

**Issue by btwolfe79** [warmuuh/libsass-maven-plugin#11]
Was wondering if it would be possible to specify multiple inputPath(s) for an execution the same way we can specify multiple includePaths (";" delimited).  We currently have common sass files for a project in one path and project specific files in another path.  Right now we have to perform two separate executions to generate the sass for the project.  

If it's an easy thing to do, it might be a nice addition to be able to have the plugin iterate over multiple separate inputPaths.

Thanks!

**Comment by jaanek** [comment]
I see that this is still an open issue at the moment. Is there any ways currently to provide multiple inputPath's or is the only way right now to fork and implement this feature?

**Comment by warmuuh** [comment]
as already mentioned, an easy solution is to add another execution stage.. 
i want to keep this plugin rather simple, so I actually see this "workaround" as not so problematic (its a one-time addition so its not even adding that much effort, also it should be possible to not  repeat the other configuration as you can configure the plugin and the execution phases separately)
the handling of multiple includePaths is actually a libsass-feature, not a libsass-maven-plugin feature.

if you really want it though, just fork and add the feature. i will close this issue for now because i am not going to implement that (due to an existing solution and limited time)
