### ISSUE TITLE
The libsass API should be its own project

### ISSUE THREAD

**Issue by jiggy** [warmuuh/libsass-maven-plugin#2]
I think that just the JNA binding for libsass should be a separate project so it can be used independently of the maven plugin. Make the binding a dependency for the mojo. Then it can be used for other build tools or dynamic compilation.

**Comment by warmuuh** [comment]
maybe you are right, but creating the jna-binding can easily be done with http://jnaerator.googlecode.com/ (as i did) and because this stuff is not in maven-central, i cannot easily factor out the bindings into a single project and refer to it.. so for now, i wont do it.. 

despite that, you can still refer to this plugin as normal dependency and can make use of the JNA bindings for e.g. gradle-plugin
