### ISSUE TITLE
Platform linux:aarch64 not supported

### ISSUE THREAD

**Issue by congweitao** [warmuuh/libsass-maven-plugin#82]
If  there is plan to support aarch64 platform in the near future ?

**Comment by xiaolin0199** [comment]
> If there is plan to support aarch64 platform in the near future ?

Have you solved this problem?

**Comment by warmuuh** [comment]
this lib is just a wrapper/plugin using https://github.com/sass/libsass, pls refer to this project instead

**Comment by martin-g** [comment]
The problem here is/was that this project uses old version of io.bit3:jsass (=> 5.7.1).
io.bit3:jsass added support for Linux ARM64 with 5.8.0 (https://github.com/bit3/jsass/commit/15b9967d67ebee770e0f5ad474f7d235ef1095fe#diff-e00d5e7ca6ac686d313fd44b408a4c90c424a3f506c783f39cd7f0decf9740ca) at Mar 25, 2019.
